### ISSUE TITLE
Compilation error on macos-13 x86_64

### ISSUE THREAD

**Issue by denehoffman** [Lokathor/wide#186] opened 2024-12-21 00:45 UTC
Part of my CI builds my crate under a few different systems for testing purposes and distribution. `wide` is a dependency of a dependency, and today I got a build error *only* on macos-13 x86_64:

```
error: cannot find macro `round_op` in this scope
   --> /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wide-0.7.30/src/f64x2_.rs:652:36
    |
652 |         Self { sse: round_m128d::<{round_op!(Nearest)}>(self.sse) }
    |                                    ^^^^^^^^

error: cannot find macro `round_op` in this scope
   --> /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wide-0.7.30/src/f32x4_.rs:683:35
    |
683 |         Self { sse: round_m128::<{round_op!(Nearest)}>(self.sse) }
    |                                   ^^^^^^^^

error: could not compile `wide` (lib) due to 2 previous errors
```

Is this something on my end, or an issue with `wide`? I don't actually use this crate directly, so forgive me if I'm barking up the wrong tree here.

**Comment by denehoffman** [comment] 2024-12-21 00:55
It looks like this commit is responsible and was a recent addition to version 0.7.30: 1587053bc99acb0881c9644e2fc6c9f194a4ce32

**Comment by Lokathor** [comment] 2024-12-21 00:55
That macro was adjusted in a version that got released today, it's possible that something got messed up with how it is exported now.

I yanked the newest version, 0.7.30, and I'll try to have a closer look when I get home.

**Comment by denehoffman** [comment] 2024-12-21 01:06
It might go further back than 0.7.30, looks like my build is still failing with 0.7.29. It's not critical, take your time.

**Comment by sd2k** [comment] 2024-12-21 09:26
I think the cause could be that https://github.com/Lokathor/safe_arch/pull/117 moved (or gated) `round_op` so it requires a feature flag to be available now?

**Comment by Lokathor** [comment] 2024-12-21 13:32
oh right, it was safearch which changed. i put the wide version back out and yanked the new safearch. things should be fixed enough for now.

**Comment by denehoffman** [comment] 2024-12-21 14:45
Can confirm my build works now, thanks for looking into this!

**Closed** 2024-12-21 14:45 UTC

**Comment by Lokathor** [comment] 2024-12-21 14:54
just put out `safe_arch-0.7.4` with the missing macro put back in the crate root. just message here again if it somehow re-broke things, but we should be safe.

**Comment by bas-ie** [comment] 2024-12-27 20:42
Thanks for this (and for your work on `wide`)! Confirmed my CI also works now :slightly_smiling_face:
